### ISSUE TITLE
👻 Boo 👻

### ISSUE THREAD

**Issue by Bob-Kerman** [SaltySchnauzer/red-vs-blue#1]
Did I scare you?
It needs models of american and russian missiles.
Super scary skeleton ghost zombie out.
👻🧟‍♂️💀👹👺
![Dude, STOP! Commiting crimes with direction and magnitude](https://user-images.githubusercontent.com/40617672/63147426-bb02d900-c030-11e9-91eb-b3664329d6a8.jpeg)

**Comment by SaltySchnauzer** [comment]
no problem kiddo, im working on graphics and cosmetics next week.
See the milestones for a rough guideline of my future workflow
